name: Run Jest Tests

on: 
  push:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Install modules
      run: npm install
      
    - name: Run tests
      run: npm test -- -u
